version: '2'

services:

### Applications Code Container #############################

    applications:
        image: tianon/true
        volumes:
            - ../:/var/www/

### Workspace Utilities Container ###########################

    workspace:
        build:
            context: ./workspace
            args:
                - INSTALL_XDEBUG=false
                - COMPOSER_GLOBAL_INSTALL=true # changed
                - INSTALL_WORKSPACE_SSH=false
                - PUID=1000
                - PGID=1000
                - TZ=UTC
        volumes_from:
            - applications
        volumes:
            - ./logs/cron:/var/log/cron
        extra_hosts:
            - "dockerhost:172.18.0.1"
        tty: true
        stdin_open: true
        restart: always

### PHP-FPM and Worker Containers ############################

    php-fpm:
        build:
            context: ./php-fpm
            args:
                - INSTALL_XDEBUG=false
                - INSTALL_BCMATH=true # changed
                - INSTALL_PHPREDIS=true # changed
                - INSTALL_OPCACHE=true
                - INTL=true
        volumes_from:
            - applications
        expose:
            - "9000"
        depends_on:
            - workspace
        extra_hosts:
            - "dockerhost:172.18.0.1"

    php-worker:
        build:
            context: ./php-worker
        volumes_from:
            - applications
        depends_on:
            - workspace

### MySQL Container #########################################

    mysql:
        build:
            context: ./mysql
        volumes:
            - ./data/mysql/:/var/lib/mysql
        restart: always

### Redis Container #########################################

    redis:
        build: ./redis
        volumes:
            - redis:/data
        restart: always

### Caddy Server Container ##################################

    caddy:
        build: ./caddy
        ports:
            - "80:80"
            - "443:443"
        volumes_from:
            - applications
        volumes:
            - ./caddy/Caddyfile.prod:/etc/Caddyfile
            - ./logs/caddy:/var/log/caddy
            - caddy:/root/.caddy
        depends_on:
            - php-fpm
        restart: always

### Volumes Setup ###########################################

volumes:
    mysql:
        driver: "local"
    redis:
        driver: "local"
    caddy:
        driver: "local"
    sessions:    ## nothing is connected to this (- ./data/sessions:/sessions)
        driver: "local"
